"""
Theme configuration for teleprinter.

Loads an optional TOML config file and exposes a ThemeConfig dataclass
that the renderer and template consume.

TOML is used for its suport of inline comments → makes the generated
default config file self-documenting without any extra tools.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

# tomllib is stdlib in Python 3.11+; tomli is its backport for 3.10.
if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomllib          # type: ignore[no-redef]
    except ImportError:
        try:
            import tomli as tomllib   # type: ignore[no-redef]
        except ImportError:
            raise ImportError(
                "Python < 3.11 requires the 'tomli' package.\n"
                "Install it with:  pip install tomli"
            )

### Default config file template 
# Written by --create-config. Keep in sync with ThemeConfig defaults.

CONFIG_TEMPLATE = """\
# teleprinter configuration file
# Generated by: python -m teleprinter --create-config
#
# Place this file in your Telegram export directory (it will be picked up
# automatically) or pass it explicitly with --config /path/to/file.toml.
# All fields are optional — remove any line to use the built-in default.

### Identity 

# Display name for the other person when their name is not in the export.
# The --partner-name CLI argument overrides this if both are given.
partner_name = ""

### Colors 
# Six-digit hex codes without the leading #.

sent_color    = "E7FBD0"   # your message bubbles       (default: light green)
recv_color    = "FFFFFF"   # their message bubbles      (default: white)
chat_bg_color = "DAD3CC"   # page background            (default: warm grey)
name_color    = "1A7FC1"   # sender name label          (default: blue)

### Background image 
# Absolute or relative (to this file) path to an image.
# The image is stretched to fill the page. Leave empty for a solid color.
background = ""

### Layout 

page_size             = "a4"   # "a4" or "letter"
font_size             = 11     # body font size in pt — 10, 11, or 12
bubble_width_fraction = 0.70   # bubble width as a fraction of the text width
                                # sensible range: 0.50 – 0.90

### Content 

show_service_messages = true   # show join/leave/pin/call events etc.
show_edited_marker    = true   # show a small "edited" label on edited messages
"""

### ThemeConfig dataclass 

@dataclass
class ThemeConfig:
    partner_name:           Optional[str]  = None
    sent_color:             str            = 'E7FBD0'
    recv_color:             str            = 'FFFFFF'
    chat_bg_color:          str            = 'DAD3CC'
    name_color:             str            = '1A7FC1'
    background:             Optional[Path] = None
    page_size:              str            = 'a4'
    font_size:              int            = 11
    bubble_width_fraction:  float          = 0.70
    show_service_messages:  bool           = True
    show_edited_marker:     bool           = True

    @property
    def page_size_latex(self) -> str:
        """Return the LaTeX geometry package paper size string."""
        return {'a4': 'a4paper', 'letter': 'letterpaper'}.get(
            self.page_size.lower(), 'a4paper'
        )


### Loading and validation 

_VALID_PAGE_SIZES = {'a4', 'letter'}
_VALID_FONT_SIZES = {10, 11, 12}


def _validate_hex(value: str, field: str) -> str:
    """Ensure value is a 6-character hex string. Strips a leading # if present."""
    value = value.lstrip('#').strip()
    if len(value) != 6:
        raise ValueError(
            f"Config field '{field}': expected a 6-digit hex color, got '{value}'."
        )
    try:
        int(value, 16)
    except ValueError:
        raise ValueError(
            f"Config field '{field}': '{value}' is not a valid hex color."
        )
    return value.upper()


def load(config_path: Path) -> ThemeConfig:
    """
    Load a TOML config file and return a ThemeConfig.

    Unknown keys are silently ignored so that future config additions
    don't break older versions of the tool.
    """
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with open(config_path, 'rb') as f:
        data = tomllib.load(f)

    cfg = ThemeConfig()

    ### Identity 
    if pn := data.get('partner_name'):
        cfg.partner_name = str(pn) if pn else None

    ### Colors 
    for field in ('sent_color', 'recv_color', 'chat_bg_color', 'name_color'):
        if field in data:
            setattr(cfg, field, _validate_hex(str(data[field]), field))

    ### Background 
    if bg := data.get('background'):
        bg_path = Path(bg)
        if not bg_path.is_absolute():
            bg_path = config_path.parent / bg_path
        if not bg_path.exists():
            raise ValueError(
                f"Config field 'background': file not found: {bg_path}"
            )
        cfg.background = bg_path.resolve()

    ### Layout 
    if ps := data.get('page_size'):
        ps = str(ps).lower()
        if ps not in _VALID_PAGE_SIZES:
            raise ValueError(
                f"Config field 'page_size': must be one of "
                f"{sorted(_VALID_PAGE_SIZES)}, got '{ps}'."
            )
        cfg.page_size = ps

    if fs := data.get('font_size'):
        fs = int(fs)
        if fs not in _VALID_FONT_SIZES:
            raise ValueError(
                f"Config field 'font_size': must be one of "
                f"{sorted(_VALID_FONT_SIZES)}, got {fs}."
            )
        cfg.font_size = fs

    if bwf := data.get('bubble_width_fraction'):
        bwf = float(bwf)
        if not 0.5 <= bwf <= 0.9:
            raise ValueError(
                f"Config field 'bubble_width_fraction': "
                f"must be between 0.5 and 0.9, got {bwf}."
            )
        cfg.bubble_width_fraction = bwf

    ### Content 
    if 'show_service_messages' in data:
        cfg.show_service_messages = bool(data['show_service_messages'])
    if 'show_edited_marker' in data:
        cfg.show_edited_marker = bool(data['show_edited_marker'])

    return cfg


def write_default_config(output_path: Path) -> None:
    """Write the default config template to output_path."""
    if output_path.exists():
        raise FileExistsError(
            f"{output_path} already exists. "
            "Delete it first or specify a different path."
        )
    output_path.write_text(CONFIG_TEMPLATE, encoding='utf-8')
    print(f"Default config written to {output_path}")
    print("Edit it, then pass it with --config or place it in your export directory.")
